# Generated by Django 4.2.6 on 2023-10-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mail_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40, unique=True, verbose_name='user_id')),
                ('subject', models.CharField(max_length=40, verbose_name='subject')),
                ('message', models.CharField(max_length=40, verbose_name='message')),
            ],
        ),
    ]
