# Generated by Django 4.2.6 on 2023-10-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automatic_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail_info',
            options={'ordering': ['id'], 'verbose_name': 'Mail_Info', 'verbose_name_plural': 'mails_info'},
        ),
        migrations.AlterModelTable(
            name='mail_info',
            table='mail_info',
        ),
    ]
