# Generated by Django 4.2.6 on 2023-12-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatic_notifications', '0002_alter_mail_info_options_alter_mail_info_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail_info',
            name='user_id',
            field=models.CharField(max_length=40, verbose_name='user_id'),
        ),
    ]
